version: "2"
services:
  web:
    extends:
      file: compose.common.yml
      service: web
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  db:
    image: postgres:9.6.1-alp-tz
