FROM ruby:2.2.4-slim

RUN apt-get update && \
  apt-get install -y build-essential node npm qt5-default libqt5webkit5-dev \
  gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x libpq-dev \
  libxml2-dev libxslt-dev

ADD Gemfile* tmp/
ADD package.json tmp/
WORKDIR /tmp
RUN gem install bundler && \
  bundle config build.nokogiri \
  --use-system-libraries && \
  bundle install && \
  npm install

RUN mkdir -p /app
WORKDIR /app

ADD . ./
