locals: &locals
  adapter: postgresql
  host: aristotle-test-db
  username: postgres
  password:
  pool: 5
  timeout: 5000

development:
  <<: *locals
  database: dev_db

test:
  <<: *locals
  database: test_db

production:
  <<: *locals
  database: prod_db
